# -*- coding: utf-8 -*-
"""gtzan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JczxXYUE7DA7uF5k2mOtfgAnOX07yCJw
"""

#!pip install -q kagglehub librosa transformers datasets evaluate accelerate torchaudio

import os
import numpy as np
import pandas as pd
import librosa
import librosa.display
import matplotlib.pyplot as plt
from tqdm import tqdm
from IPython.display import Audio
import warnings
warnings.filterwarnings("ignore")
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import torch
import torchaudio
from datasets.features import audio
from transformers import AutoModelForAudioClassification
from datasets import Dataset
from transformers import AutoFeatureExtractor
from transformers import TrainingArguments
from transformers import Trainer
from transformers import EarlyStoppingCallback
import pickle
from sklearn.metrics import accuracy_score , f1_score ,classification_report

import kagglehub
path = kagglehub.dataset_download("andradaolteanu/gtzan-dataset-music-genre-classification")

folder = os.path.join(path,"Data")
sound = os.listdir(folder)
sound

genres_path = os.path.join(folder, "genres_original")
print(os.listdir(genres_path))

audio_paths = []
labels = []
for genre in os.listdir(genres_path):
    genre_folder = os.path.join(genres_path, genre)
    if os.path.isdir(genre_folder):
        for file in os.listdir(genre_folder):
            if file.endswith(".wav"):
                audio_paths.append(os.path.join(genre_folder, file))
                labels.append(genre)

df = pd.DataFrame({
    "path": audio_paths,
    "label": labels
})

print(df.shape)
df.head()
  #

print(df.shape)
df["label"].value_counts()

train_df, test_df = train_test_split(df, test_size=0.2, random_state=42,stratify=df["label"])
print(train_df.shape, test_df.shape)

encoder = LabelEncoder()
train_df["label"] = encoder.fit_transform(train_df["label"])
test_df["label"] = encoder.transform(test_df["label"])
print(train_df.shape, test_df.shape)
print(encoder.classes_)
train_df.head()

train_huggingface = Dataset.from_pandas(train_df)
test_huggingface = Dataset.from_pandas(test_df)
print(train_huggingface)
print(test_huggingface)

feature_extractor = AutoFeatureExtractor.from_pretrained("MIT/ast-finetuned-audioset-10-10-0.4593")
print(feature_extractor.sampling_rate)
print(feature_extractor)

def preprocess_audio(example) :
  try:
      audio, sr = librosa.load(example["path"],sr=16000,duration=5)
      inputs = feature_extractor([audio], sampling_rate=sr,max_length=sr*5,truncation=True,padding="max_length",return_tensors="pt")
      example["input_values"] = inputs["input_values"].squeeze(0)

  except Exception as e:
      print(f"Error processing audio for path: {example['path']}. Error: {e}")
      example["input_values"] = None

  return example

sample = preprocess_audio(train_df.iloc[0].to_dict())

print(sample.keys())
print(sample["input_values"].shape)

train_huggingface = train_huggingface.map(preprocess_audio)
test_huggingface = test_huggingface.map(preprocess_audio)

train_huggingface = train_huggingface.filter(lambda x: x["input_values"] is not None)
test_huggingface = test_huggingface.filter(lambda x: x["input_values"] is not None)
print(train_huggingface.num_rows)
print(test_huggingface.num_rows)

model = AutoModelForAudioClassification.from_pretrained("MIT/ast-finetuned-audioset-10-10-0.4593",num_labels=len(encoder.classes_),    ignore_mismatched_sizes=True)
print(model.config.num_labels)

training_args = TrainingArguments(
    output_dir="./ast_genre",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=5,
    weight_decay=0.01,
    logging_steps=10,
    load_best_model_at_end=True,
    metric_for_best_model="eval_accuracy",
    greater_is_better=False,
    optim="adamw_torch"

)

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    return {
        "accuracy": accuracy_score(labels, predictions)
    }

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_huggingface,
    eval_dataset=test_huggingface,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(
        early_stopping_patience=3,
        early_stopping_threshold=0.0
    )]
)

trainer.train()

trainer.save_model("genre_model")
feature_extractor.save_pretrained("genre_model")

history = trainer.state.log_history

with open("label_encoder_genre.pkl", "wb") as f:
    pickle.dump(encoder, f)

predictions = trainer.predict(test_huggingface)

y_pred = np.argmax(predictions.predictions, axis=-1)
y_true = test_huggingface["label"]
print(classification_report(y_true, y_pred, target_names=encoder.classes_))

cm = confusion_matrix(y_true, y_pred)
cm_df = pd.DataFrame(cm, index=encoder.classes_, columns=encoder.classes_)
plt.figure(figsize=(10, 8))
sns.heatmap(cm_df, annot=True, fmt="d", cmap="Blues")
plt.title("Confusion Matrix")
plt.xlabel("Predicted Labels")
plt.ylabel("True Labels")
plt.savefig("confusion_matrix_gtzan.png")
plt.show()

train_losses_by_epoch = {}
epoch_eval_data = []

for log in history:
    if 'loss' in log and 'eval_loss' not in log:
        current_epoch_float = log['epoch']
        current_epoch_int = int(current_epoch_float)
        if current_epoch_int not in train_losses_by_epoch:
            train_losses_by_epoch[current_epoch_int] = []
        train_losses_by_epoch[current_epoch_int].append(log['loss'])
    elif 'eval_loss' in log:
        epoch_eval_data.append((log['epoch'], log['eval_loss'], log['eval_accuracy']))

epochs_final = sorted(list(set([data[0] for data in epoch_eval_data])))

averaged_train_losses = []
final_eval_losses = []
final_eval_accuracies = []

for epoch_num in epochs_final:
    int_epoch = int(epoch_num)
    if int_epoch in train_losses_by_epoch:
        averaged_train_losses.append(np.mean(train_losses_by_epoch[int_epoch]))
    else:
        averaged_train_losses.append(None)

    found_eval = False
    for eval_entry_epoch, eval_loss_val, eval_acc_val in epoch_eval_data:
        if eval_entry_epoch == epoch_num:
            final_eval_losses.append(eval_loss_val)
            final_eval_accuracies.append(eval_acc_val)
            found_eval = True
            break
    if not found_eval:
        final_eval_losses.append(None)
        final_eval_accuracies.append(None)

plot_epochs = []
plot_train_loss = []
plot_eval_loss = []
plot_eval_acc = []

for i, epoch in enumerate(epochs_final):
    if averaged_train_losses[i] is not None and final_eval_losses[i] is not None:
        plot_epochs.append(epoch)
        plot_train_loss.append(averaged_train_losses[i])
        plot_eval_loss.append(final_eval_losses[i])
        plot_eval_acc.append(final_eval_accuracies[i])


#
plt.figure(figsize=(8,5))
plt.plot(plot_eval_acc, marker='o')
plt.title("Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.figure(figsize=(8,5))
plt.plot(plot_eval_loss, marker='o')
plt.title("Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.show()

plt.figure(figsize=(10, 6))
plt.plot(plot_epochs, plot_train_loss, marker='o', label='Training Loss')
plt.plot(plot_epochs, plot_eval_loss, marker='o', label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training and Validation Loss Over Epochs')
plt.legend()
plt.grid(True)
plt.savefig("loss_gtzan.png")
plt.show()

trainer.evaluate()
predictions.metrics

#!zip -r genre_model.zip genre_model label_encoder.pkl