# -*- coding: utf-8 -*-
"""IRMAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XEDEI7W-Sjvbdtdpa1_Acje3FUbhm117
"""

import os
import numpy as np
import pandas as pd
import librosa
import librosa.display
import matplotlib.pyplot as plt
from tqdm import tqdm
from IPython.display import Audio
import warnings
warnings.filterwarnings("ignore")
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import torch
import torchaudio
from datasets.features import audio
from transformers import AutoModelForAudioClassification
from datasets import Dataset
from transformers import AutoFeatureExtractor
from transformers import TrainingArguments
from transformers import Trainer
from transformers import EarlyStoppingCallback
import pickle
from sklearn.metrics import accuracy_score , f1_score ,classification_report

import kagglehub
path = kagglehub.dataset_download("urvishp80/irmas-training-data")

print(path)
print(os.listdir(path))

for root, dirs, files in os.walk(path):
    print(root)
    print("Folders:", dirs[:5])
    print("Files:", files[:5])
    break
dataset_path = os.path.join(path, "IRMAS-TrainingData")

print(os.listdir(dataset_path))

rows = []

for label in os.listdir(dataset_path):
    label_path = os.path.join(dataset_path, label)
    if os.path.isdir(label_path):
          for filename in os.listdir(label_path):
             if filename.endswith(".wav"):
                file_path = os.path.join(label_path, filename)
                rows.append({"path": file_path, "label": label})

df = pd.DataFrame(rows)
print(df.shape)
df.head()
print(df["label"].value_counts())

encoder = LabelEncoder()
df["label"] = encoder.fit_transform(df["label"])
print(df.head())

train_df,test_df= train_test_split(df,test_size=0.2,random_state=42,stratify=df["label"])

train_df=Dataset.from_pandas(train_df)
test_df=Dataset.from_pandas(test_df)
print(train_df)
print(test_df)

feature_extractor = AutoFeatureExtractor.from_pretrained("MIT/ast-finetuned-audioset-10-10-0.4593")
print(feature_extractor)

def preprocess_function(example):
  audio , sr = librosa.load(example["path"],sr=16000,duration=3)
  inputs = feature_extractor(audio, sampling_rate=sr, return_tensors="pt", padding=True)
  example["input_values"] = inputs.input_values[0]
  return example

train_df = train_df.map(preprocess_function)
test_df = test_df.map(preprocess_function)
train_df = train_df.filter(lambda example: example.get("input_values") is not None)
test_df = test_df.filter(lambda example: example.get("input_values") is not None)

model = AutoModelForAudioClassification.from_pretrained("MIT/ast-finetuned-audioset-10-10-0.4593", num_labels=len(encoder.classes_),ignore_mismatched_sizes=True)
print(model.config.num_labels)

training_args = TrainingArguments(
    output_dir="./ast_genre",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=5,
    weight_decay=0.01,
    logging_steps=10,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    optim="adamw_torch"
)

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    return {
        "accuracy": accuracy_score(labels, predictions)
    }

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_df,
    eval_dataset=test_df,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(
        early_stopping_patience=5,
        early_stopping_threshold=0.0
    )]
)

trainer.train()

history = trainer.state.log_history

predictions = trainer.predict(test_df)

y_pred = np.argmax(predictions.predictions, axis=1)
y_true = test_df["label"]

cls=classification_report(y_true,y_pred,target_names=encoder.classes_)
print(cls)

cm = confusion_matrix(y_true, y_pred)
cm_df = pd.DataFrame(cm, index=encoder.classes_, columns=encoder.classes_)
plt.figure(figsize=(10, 8))
sns.heatmap(cm_df, annot=True, fmt="d", cmap="Blues")
plt.title("Confusion Matrix")
plt.xlabel("Predicted Labels")
plt.ylabel("True Labels")
plt.savefig("confusion_matrix_irmas.png")
plt.show()

train_losses_by_epoch = {}
epoch_eval_data = []

for log in history:
    if 'loss' in log and 'eval_loss' not in log:
        current_epoch_float = log['epoch']
        current_epoch_int = int(current_epoch_float)
        if current_epoch_int not in train_losses_by_epoch:
            train_losses_by_epoch[current_epoch_int] = []
        train_losses_by_epoch[current_epoch_int].append(log['loss'])
    elif 'eval_loss' in log:
        epoch_eval_data.append((log['epoch'], log['eval_loss'], log['eval_accuracy']))

epochs_final = sorted(list(set([data[0] for data in epoch_eval_data])))

averaged_train_losses = []
final_eval_losses = []
final_eval_accuracies = []

for epoch_num in epochs_final:
    int_epoch = int(epoch_num)
    if int_epoch in train_losses_by_epoch:
        averaged_train_losses.append(np.mean(train_losses_by_epoch[int_epoch]))
    else:
        averaged_train_losses.append(None)

    found_eval = False
    for eval_entry_epoch, eval_loss_val, eval_acc_val in epoch_eval_data:
        if eval_entry_epoch == epoch_num:
            final_eval_losses.append(eval_loss_val)
            final_eval_accuracies.append(eval_acc_val)
            found_eval = True
            break
    if not found_eval:
        final_eval_losses.append(None)
        final_eval_accuracies.append(None)

plot_epochs = []
plot_train_loss = []
plot_eval_loss = []
plot_eval_acc = []

for i, epoch in enumerate(epochs_final):
    if averaged_train_losses[i] is not None and final_eval_losses[i] is not None:
        plot_epochs.append(epoch)
        plot_train_loss.append(averaged_train_losses[i])
        plot_eval_loss.append(final_eval_losses[i])
        plot_eval_acc.append(final_eval_accuracies[i])


#
plt.figure(figsize=(8,5))
plt.plot(plot_eval_acc, marker='o')
plt.title("Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.figure(figsize=(8,5))
plt.plot(plot_eval_loss, marker='o')
plt.title("Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.show()

plt.figure(figsize=(10, 6))
plt.plot(plot_epochs, plot_train_loss, marker='o', label='Training Loss')
plt.plot(plot_epochs, plot_eval_loss, marker='o', label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training and Validation Loss Over Epochs')
plt.legend()
plt.grid(True)
plt.savefig("loss_irmas.png")
plt.show()

with open("label_encoder_IRMAS.pkl", "wb") as f:
    pickle.dump(encoder, f)

trainer.save_model("irmas_model")
feature_extractor.save_pretrained("irmas_model")

trainer.evaluate()
predictions.metrics

!zip -r irmas_model.zip irmas_model label_encoder_IRMAS.pkl

from google.colab import files
files.download("irmas_model.zip")